# Generated by Django 3.1.7 on 2021-03-31 18:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarshipID', models.CharField(max_length=100)),
                ('denomination', models.CharField(max_length=255)),
                ('referred_studies', models.CharField(max_length=255)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('criteria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolID', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('school_type', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone_1', models.CharField(max_length=255)),
                ('contact_phone_2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_type', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=255)),
                ('phone_1', models.CharField(max_length=255)),
                ('phone_2', models.CharField(max_length=255)),
                ('date_of_birth_day', models.CharField(max_length=2)),
                ('date_of_b6irth_month', models.CharField(max_length=2)),
                ('date_of_birth_year', models.CharField(max_length=4)),
                ('city_of_birth', models.CharField(max_length=255)),
                ('province_of_birth', models.CharField(max_length=255)),
                ('country_of_birth', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
                ('marital_status', models.IntegerField()),
                ('number_of_children', models.IntegerField(default=0)),
                ('occupation', models.CharField(max_length=255)),
                ('employer_name', models.CharField(max_length=255)),
                ('employer_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tuition_Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_level', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=255)),
                ('tuition', models.CharField(max_length=255)),
                ('clothing', models.CharField(max_length=255)),
                ('furniture', models.CharField(max_length=255)),
                ('books', models.CharField(max_length=255)),
                ('misc', models.CharField(max_length=255)),
                ('schoolID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_on', models.DateField(default=datetime.date.today)),
                ('delivery_method', models.CharField(max_length=255)),
                ('award_justification', models.CharField(max_length=255)),
                ('awarded_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scholarshipID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.scholarship')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Hollow_Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hollow_year', models.CharField(max_length=255)),
                ('activities', models.CharField(max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_attended', models.CharField(max_length=4)),
                ('class_name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('dismissed', models.IntegerField(default=0)),
                ('dismissal_reason', models.CharField(max_length=255)),
                ('schoolID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.school')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship_Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('academic_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donorID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.user')),
                ('scholarshipID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.scholarship')),
            ],
        ),
    ]
